#!/usr/bin/env python
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream

#Variables that contains the user credentials to access Twitter API 

access_token = "4228035318-DbQPCpfOsbb4uFRztbR8QVamuQL7fJnYnWhsN7i"
access_token_secret = "9N2wmHp8OVBfYgHqnV3wASEy6JtGIgFnMfSD5CXbJBI20"
consumer_key = "E98J8oZPMdTwN3r2KyflNf71A"
consumer_secret = "eI9ulGU10skpH4gmhby2AamfGsK5r5C81IIP4vE8PBpqbrEwog"

#This is a basic listener that just prints received tweets to stdout.

class StdOutListener(StreamListener):
    def on_data(self, data):
        print data
        return True
  def on_error(self, status):
        print status
 if __name__ == '__main__':

#This handles Twitter authetification and the connection to Twitter Streaming API

l = StdOutListener()
auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
stream = Stream(auth, l)

#This line filter Twitter Streams to capture data by the keywords

stream.filter(track=['globalwarming', 'global warming', 'ParisClimateConference', 'cybermonday','LHHHReunion','wine','beer','whisky','rum','vodka'])
